name: Lua CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    uses: FPtje/GLuaFixer/.github/workflows/glualint.yml@master
        with:
          config: .glualint.json

    steps:
      - uses: actions/checkout@v3

      - uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check lua/
