name: Lua CI

on:
  push:
    paths:
      - "**.json"
      - "**.yml"
      - "**.toml"
      - "**.lua"
      - ".gitattributes"
      - ".editorconfig"
  pull_request:
    paths:
      - "**.json"
      - "**.yml"
      - "**.toml"
      - "**.lua"
      - ".gitattributes"
      - ".editorconfig"

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GLUAFIXER_VERSION: 1.23.0

    steps:
      - uses: actions/checkout@v3

      - uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check lua/

      - name: Download GLuaFixer
        run: |
          curl --retry 3 --location https://github.com/FPtje/GLuaFixer/releases/download/$GLUAFIXER_VERSION/glualint-$GLUAFIXER_VERSION-x86_64-linux.zip --output gluafixer.zip
          unzip gluafixer.zip

      - name: Run GLuaFixer
        run: ./glualint --output-format github --config .glualint.json lint lua

  deploy:
    runs-on: ubuntu-latest
    needs: [lint]
    if: ${{ format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }}

    environment: production
    concurrency: production

    steps:
      - name: Post to webhook
        run: curl -X POST ${{ secrets.DEPLOYER_WEBHOOK }}/${{ github.event.repository.name }}
